from collections.abc import Callable
from collections.abc import Hashable
from collections.abc import Iterable
from collections.abc import Iterator
from collections.abc import Sequence
from typing import Any
from typing import Concatenate
from typing import Generic
from typing import ParamSpec
from typing import TypeVar
from typing import TypeVarTuple
from typing import overload

from _typeshed import FileDescriptorOrPath
from _typeshed import SupportsGetItem

__version__: str

_T = TypeVar('_T')
_R = TypeVar('_R')
_K = TypeVar('_K')
_V = TypeVar('_V')
_S = TypeVar('_S', str, bytes)
_Ts = TypeVarTuple('_Ts')
_P = ParamSpec('_P')


class B:
    f: Any
    args: tuple[Any, ...]
    kw: dict[str, Any]
    def __init__(self, f: Any = ..., *args: Any, **kw: Any) -> None: ...


class Pipe(B, Generic[_R]):
    @overload
    def __new__(cls, f: type[list[Any]], /) -> _PipeToList: ...
    @overload
    def __new__(cls, f: type[tuple[Any, ...]], /) -> _PipeToTuple: ...
    @overload
    def __new__(cls, f: type[set[Any]], /) -> _PipeToSet: ...
    @overload
    def __new__(cls, f: type[frozenset[Any]], /) -> _PipeToFrozenSet: ...
    @overload
    def __new__(cls, f: type[dict[Any, Any]], /) -> _PipeToDict: ...
    @overload
    def __new__(cls, f: Callable[Concatenate[Any, _P], _R], /, *args: _P.args, **kw: _P.kwargs) -> Pipe[_R]: ...
    def __ror__(self, x: Any, /) -> _R: ...


class _PipeToList(Pipe[list[Any]]):
    def __ror__(self, x: Iterable[_T], /) -> list[_T]: ...


class _PipeToTuple(Pipe[tuple[Any, ...]]):
    def __ror__(self, x: Iterable[_T], /) -> tuple[_T, ...]: ...


class _PipeToSet(Pipe[set[Any]]):
    def __ror__(self, x: Iterable[_T], /) -> set[_T]: ...


class _PipeToFrozenSet(Pipe[frozenset[Any]]):
    def __ror__(self, x: Iterable[_T], /) -> frozenset[_T]: ...


class _PipeToDict(Pipe[dict[Any, Any]]):
    def __ror__(self, x: Iterable[tuple[_K, _V]], /) -> dict[_K, _V]: ...


class Map(B, Generic[_R]):
    def __init__(self, f: Callable[[Any], _R]) -> None: ...
    def __ror__(self, it: Iterable[Any], /) -> Iterator[_R]: ...


class Filter(B):
    def __init__(self, f: Callable[[Any], object]) -> None: ...
    def __ror__(self, it: Iterable[_T], /) -> Iterator[_T]: ...


class Reduce(B, Generic[_R]):
    @overload
    def __init__(self, f: Callable[[Any, Any], _R], /) -> None: ...
    @overload
    def __init__(self, f: Callable[[Any, Any], Any], initial: _R, /) -> None: ...
    def __ror__(self, it: Iterable[Any], /) -> _R: ...


class MapKeys(B, Generic[_R]):
    def __init__(self, f: Callable[[Any], _R]) -> None: ...
    def __ror__(self, it: Iterable[tuple[Any, _V]], /) -> Iterator[tuple[_R, _V]]: ...


class MapValues(B, Generic[_R]):
    def __init__(self, f: Callable[[Any], _R]) -> None: ...
    def __ror__(self, it: Iterable[tuple[_K, Any]], /) -> Iterator[tuple[_K, _R]]: ...


class FilterFalse(B):
    def __init__(self, f: Callable[[Any], object]) -> None: ...
    def __ror__(self, it: Iterable[_T], /) -> Iterator[_T]: ...


class FilterKeys(B):
    def __init__(self, f: Callable[[Any], object] | None = ...) -> None: ...
    def __ror__(self, it: Iterable[_T], /) -> Iterator[_T]: ...


class FilterValues(B):
    def __init__(self, f: Callable[[Any], object] | None = ...) -> None: ...
    def __ror__(self, it: Iterable[_T], /) -> Iterator[_T]: ...


class FlatMap(B, Generic[_R]):
    def __init__(self, f: Callable[[Any], Iterable[_R]]) -> None: ...
    def __ror__(self, it: Iterable[Any], /) -> Iterator[_R]: ...


class FlatMapValues(B, Generic[_R]):
    def __init__(self, f: Callable[[Any], Iterable[_R]]) -> None: ...
    def __ror__(self, it: Iterable[tuple[_K, Any]], /) -> Iterator[tuple[_K, _R]]: ...


class KeyBy(B, Generic[_R]):
    def __init__(self, f: Callable[[Any], _R]) -> None: ...
    def __ror__(self, it: Iterable[_T], /) -> Iterator[tuple[_R, _T]]: ...


class ValueBy(B, Generic[_R]):
    def __init__(self, f: Callable[[Any], _R]) -> None: ...
    def __ror__(self, it: Iterable[_T], /) -> Iterator[tuple[_T, _R]]: ...


class Append(B, Generic[_R]):
    def __init__(self, f: Callable[[Any], _R]) -> None: ...
    def __ror__(self, it: Iterable[tuple[*_Ts]], /) -> Iterator[tuple[*_Ts, _R]]: ...


class Keys(B):
    def __init__(self) -> None: ...
    def __ror__(self, it: Iterable[tuple[_K, Any]], /) -> Iterator[_K]: ...


class Values(B):
    def __init__(self) -> None: ...
    def __ror__(self, it: Iterable[tuple[Any, _V]], /) -> Iterator[_V]: ...


class SwapKV(B):
    def __init__(self) -> None: ...
    def __ror__(self, it: Iterable[tuple[_K, _V]], /) -> Iterator[tuple[_V, _K]]: ...


class Grep(B, Generic[_S]):
    def __init__(self, f: _S, *, v: bool = ..., i: bool = ...) -> None: ...
    def __ror__(self, it: Iterable[_S], /) -> Iterator[_S]: ...


class IterLines(B):
    def __init__(self, *, strip: bool = ...) -> None: ...
    def __ror__(self, f: FileDescriptorOrPath, /) -> Iterator[str]: ...


class Count(B):
    def __init__(self) -> None: ...
    def __ror__(self, it: Iterable[Any], /) -> int: ...


class Slice(B):
    @overload
    def __init__(self, stop: int | None, /) -> None: ...
    @overload
    def __init__(self, start: int | None, stop: int | None, step: int | None = ..., /) -> None: ...
    def __ror__(self, it: Iterable[_T], /) -> Iterator[_T]: ...


class Take(B):
    def __init__(self, f: int) -> None: ...
    def __ror__(self, it: Iterable[_T], /) -> list[_T]: ...


class Sorted(B):
    def __init__(self, *, key: Callable[[Any], Any] | None = ..., reverse: bool = ...) -> None: ...
    def __ror__(self, it: Iterable[_T], /) -> list[_T]: ...


class GroupBy(B, Generic[_R]):
    def __init__(self, f: Callable[[Any], _R]) -> None: ...
    def __ror__(self, it: Iterable[_T], /) -> Iterator[tuple[_R, Iterator[_T]]]: ...


class ReduceByKey(B):
    def __init__(self, f: Callable[[Any, Any], Any]) -> None: ...
    def __ror__(self, it: Iterable[tuple[_K, _V]], /) -> list[tuple[_K, _V]]: ...


class Apply(B):
    def __init__(self, f: Callable[[Any], Any]) -> None: ...
    def __ror__(self, x: _T, /) -> _T: ...


class StarPipe(B, Generic[_R]):
    def __init__(self, f: Callable[..., _R]) -> None: ...
    def __ror__(self, x: Iterable[Any], /) -> _R: ...


class StarMap(B, Generic[_R]):
    def __init__(self, f: Callable[..., _R]) -> None: ...
    def __ror__(self, x: Iterable[Iterable[Any]], /) -> Iterator[_R]: ...


class StarFlatMap(B, Generic[_R]):
    def __init__(self, f: Callable[..., Iterable[_R]]) -> None: ...
    def __ror__(self, x: Iterable[Iterable[Any]], /) -> Iterator[_R]: ...


class MapApply(B):
    def __init__(self, f: Callable[[Any], Any]) -> None: ...
    def __ror__(self, it: Iterable[_T], /) -> Iterator[_T]: ...


class Switch(B, Generic[_R]):
    # cases are re-iterated on every use, so a one-shot iterator would match at most once
    def __init__(self, f: Sequence[tuple[Callable[[Any], object], Callable[[Any], _R]]]) -> None: ...
    def __ror__(self, x: _T, /) -> _T | _R: ...


class MapSwitch(B, Generic[_R]):
    def __init__(self, f: Sequence[tuple[Callable[[Any], object], Callable[[Any], _R]]]) -> None: ...
    def __ror__(self, it: Iterable[_T], /) -> Iterator[_T | _R]: ...


class YieldIf(B, Generic[_R]):
    @overload
    def __new__(cls, f: None = ..., *, key: Callable[[Any], object] = ...) -> _YieldIfSame: ...
    @overload
    def __new__(cls, f: Callable[[Any], _R], *, key: Callable[[Any], object] = ...) -> YieldIf[_R]: ...
    def __ror__(self, it: Iterable[Any], /) -> Iterator[_R]: ...


class _YieldIfSame(YieldIf[Any]):
    def __ror__(self, it: Iterable[_T], /) -> Iterator[_T]: ...


class Join(B, Generic[_V]):
    # the right side is re-iterated per left item, so a one-shot iterator would join only the first one
    def __init__(self, f: Sequence[_V], *, key: Callable[[Any, Any], object] = ...) -> None: ...
    def __ror__(self, it: Iterable[_T], /) -> Iterator[tuple[_T, _V]]: ...


class GetItem(B, Generic[_K]):
    def __init__(self, f: _K) -> None: ...
    def __ror__(self, x: SupportsGetItem[_K, _V], /) -> _V: ...


class SetItem(B):
    def __init__(self, f: Any, value: Any, /) -> None: ...
    def __ror__(self, x: _T, /) -> _T: ...


class DelItem(B):
    def __init__(self, f: Any) -> None: ...
    def __ror__(self, x: _T, /) -> _T: ...


class GetAttr(B):
    def __init__(self, f: str) -> None: ...
    def __ror__(self, x: Any, /) -> Any: ...


class SetAttr(B):
    def __init__(self, f: str, value: Any, /) -> None: ...
    def __ror__(self, x: _T, /) -> _T: ...


class DelAttr(B):
    def __init__(self, f: str) -> None: ...
    def __ror__(self, x: _T, /) -> _T: ...


class MapGetItem(B, Generic[_K]):
    def __init__(self, f: _K) -> None: ...
    def __ror__(self, it: Iterable[SupportsGetItem[_K, _V]], /) -> Iterator[_V]: ...


class MapSetItem(B):
    def __init__(self, f: Any, value: Any, /) -> None: ...
    def __ror__(self, it: Iterable[_T], /) -> Iterator[_T]: ...


class MapDelItem(B):
    def __init__(self, f: Any) -> None: ...
    def __ror__(self, it: Iterable[_T], /) -> Iterator[_T]: ...


class MapGetAttr(B):
    def __init__(self, f: str) -> None: ...
    def __ror__(self, it: Iterable[Any], /) -> Iterator[Any]: ...


class MapSetAttr(B):
    def __init__(self, f: str, value: Any, /) -> None: ...
    def __ror__(self, it: Iterable[_T], /) -> Iterator[_T]: ...


class MapDelAttr(B):
    def __init__(self, f: str) -> None: ...
    def __ror__(self, it: Iterable[_T], /) -> Iterator[_T]: ...


class MethodCaller(B):
    def __init__(self, f: str, *args: Any, **kw: Any) -> None: ...
    def __ror__(self, x: Any, /) -> Any: ...


class MapMethodCaller(B):
    def __init__(self, f: str, *args: Any, **kw: Any) -> None: ...
    def __ror__(self, it: Iterable[Any], /) -> Iterator[Any]: ...


class Unique(B):
    def __init__(self, f: Callable[[Any], Hashable] | None = ...) -> None: ...
    def __ror__(self, it: Iterable[_T], /) -> Iterator[_T]: ...


class Exec(B):
    def __init__(self, f: Callable[..., Any], *args: Any, **kw: Any) -> None: ...
    def __ror__(self, x: _T, /) -> _T: ...


class Chunked(B):
    def __init__(self, f: int) -> None: ...
    def __ror__(self, it: Iterable[_T], /) -> Iterator[tuple[_T, ...]]: ...
